### ISSUE TITLE
Invalid links in v1.1.1 module.json

### ISSUE THREAD

**Issue by brossz** [HadaIonut/WallCutter#3]
There is an inconsistency in the v1.1.1 release (https://github.com/HadaIonut/WallCutter/releases/download/1.1.1/module.json) that causes the download to fail within Foundry.  The release is tagged as 1.1.1, but the module json uses v1.1.1 for the download links.  Can be quickly solved two different ways: 

1. Change the release tag from 1.1.1 to v1.1.1 to make it consistent with your previous releases and allow the links in the file to work.
2. Change the links within the 1.1.1 module.json to point to 1.1.1 instead of v1.1.1 as indicated below:
https://github.com/HadaIonut/WallCutter/releases/download/1.1.1/module.json
https://github.com/HadaIonut/WallCutter/releases/download/1.1.1/WallCutter.zip

**Comment by HadaIonut** [comment]
Thank you very much, I have not noticed i did that, it should be fixed now
